### ISSUE TITLE
ots login causes traceback

### ISSUE THREAD

**Issue by aisopuro** [hegenator/ots#1]
Having freshly installed `ots` from the `dev` branch, I was able to succesfully run `ots --help`, outputting
```
~ $ ots --help
Usage: ots [OPTIONS] COMMAND [ARGS]...

  Simple tool to record your time usage and send it to Odoo.

Options:
  --help  Show this message and exit.

Commands:
  add     Adds a timesheet entry without starting it.
  alias   Create an alias for a timesheet.
  drop    Drops a timesheet.
  edit    Edit information on an existing timesheet.
  list    Lists all timesheets for a given number of days, starting from a...
  login   Login to Odoo and save the session.
  logout  Log out of Odoo and remove the saved session.
  lunch   Starts a lunch timesheet.
  push    Push timesheets to Odoo.
  resume  Resume a timesheet of the given index.
  search  Searches for a task in Odoo.
  setup   Set up basic configurations.
  start   Start a new recording.
  stop    Stop the currently running time recording.
  sync    Synchronise the timesheets with Odoo.
  update  Update the project/task information of a timesheet from Odoo.
```
I installed `ots` by cloning it onto my machine's `github` directory and then pip-installing it as editable to my user: `pip3 install --user -e github/ots`.

Running `ots login` caused a traceback (below). Is it possible the command is not properly initializing the `.otk` directory?

The trace:
```
Traceback (most recent call last):
  File "/home/atte/.local/lib/python3.6/site-packages/zc/lockfile/__init__.py", line 81, in __init__
    fp = open(path, 'r+')
FileNotFoundError: [Errno 2] No such file or directory: '/home/atte/.ots/filestore.fs.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/atte/.local/bin/ots", line 11, in <module>
    load_entry_point('Odoo-TimeSheets', 'console_scripts', 'ots')()
  File "/home/atte/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/atte/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/atte/.local/lib/python3.6/site-packages/click/core.py", line 1134, in invoke
    Command.invoke(self, ctx)
  File "/home/atte/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/atte/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/atte/.local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/atte/github/ots/ots/cli.py", line 59, in cli
    file_storage = FileStorage.FileStorage(str(Path(OTS_PATH) / filestore_file_name))
  File "/home/atte/.local/lib/python3.6/site-packages/ZODB/FileStorage/FileStorage.py", line 242, in __init__
    self._lock_file = LockFile(file_name + '.lock')
  File "/home/atte/.local/lib/python3.6/site-packages/zc/lockfile/__init__.py", line 117, in __init__
    super(LockFile, self).__init__(path)
  File "/home/atte/.local/lib/python3.6/site-packages/zc/lockfile/__init__.py", line 87, in __init__
    fp = open(path, 'a+')
FileNotFoundError: [Errno 2] No such file or directory: '/home/atte/.ots/filestore.fs.lock'
```

**Comment by hegenator** [comment]
Hmm, interesting indeed. I can replicate this in a virtual env, so I'll see if I can figure out what the problem is.

**Comment by hegenator** [comment]
The problem was indeed that the `.ots` directory was not being initialized if it didn't already exist, and I hadn't noticed because I probably created it by hand in the beginning of the project.

The commit 35c9bf5 in dev branch should fix this issue.
