### ISSUE TITLE
[BUG] Fails on task update for an entry

### ISSUE THREAD

**Issue by Tatider** [hegenator/ots#5]
```
>>> ots edit --task-id=123 1
Traceback (most recent call last):
  File "/usr/local/bin/ots", line 11, in <module>
    load_entry_point('Odoo-TimeSheets', 'console_scripts', 'ots')()
  File "/Users/deribina/Library/Python/3.7/lib/python/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/deribina/Library/Python/3.7/lib/python/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/deribina/Library/Python/3.7/lib/python/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/deribina/Library/Python/3.7/lib/python/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/deribina/Library/Python/3.7/lib/python/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/deribina/Library/Python/3.7/lib/python/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/deribina/workspace/tools/repos/ots/ots/cli.py", line 184, in edit
    project_id=project_id,
  File "/Users/deribina/workspace/tools/repos/ots/ots/timesheet_filestore.py", line 202, in edit_timesheet
    return timesheet.edit(**kwargs)
  File "/Users/deribina/workspace/tools/repos/ots/ots/timesheet.py", line 116, in edit
    task_id_edited = self.set_task_id(task_id)
AttributeError: 'TimeSheet' object has no attribute 'set_task_id'
```

**Comment by hegenator** [comment]
Shiet. I noticed that thing missing for the project earlier, but didn't have the sense to make sure the same works for task_id.

I've pushed a commit to `dev` that should fix this, but I've not exactly tested it yet. 
https://github.com/hegenator/ots/commit/1bf3e8528045709204d5de92a7f6d849d11b1e1a
